server:
  port: 8080
  servlet:
    context-path: /

spring:

  datasource:
    url: jdbc:mariadb://localhost:3306/lionshop?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql : true # sql 예쁘게 출력
        default_batch_fetch_size: 1000

    show-sql: true  # sql 출력
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB # 파일 업로드 요청 시 하나의 파일 크기 10MB로 제한
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일의 크기의합 100MB로 제한
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.hibernate.type: trace

file:
  upload:
    path: /Users/jang/shop/

kakao:
  client:
    id: 12791195a7eeb300d4d883093b93b1eb
    secret: 1giLrMm9d1dFu75lCjQI8HTtrmG07lmT

token:
  secret: estsoft-externship # todo 자신의 jwt token secret키 입력
  access-token-expiration-time: 900000  # 15분
  refresh-token-expiration-time: 1210500000 # 2주
