server:
  port: 8080
  servlet:
    context-path: /

spring:
  h2:
    console:
      enabled: true

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:lionshop
      driver-class-name: org.h2.Driver
      username: root
      password: 1234

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql : true # sql 예쁘게 출력
        default_batch_fetch_size: 1000

    show-sql: true  # sql 출력

  jackson:
    property-naming-strategy: SNAKE_CASE

file:
  upload:
    path: /Users/jang/shop/  # 윈도우파일 경로 예시 : C:/shop/